services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: bark
      MYSQL_USER: xtr
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
#    volumes:
#      - /var/run/mysqld:/var/run/mysqld
#      - /var/lib/mysql:/var/lib/mysql:rw
#      #- ./data:/var/lib/mysql:rw # <- permissions
#    user: root
