services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: bark
      MYSQL_USER: xtr
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
